### ISSUE TITLE
Some video tutorials?

### ISSUE THREAD

**Issue by Jonatthu** [swmitra/html-designer#1]
'I want to use the animate transitions css3, How can I perform this?

**Comment by swmitra** [comment]
Sure. I will capture the transition workflow and post a link for the same in wiki

**Comment by Jonatthu** [comment]
thanks for your time!

**Comment by swmitra** [comment]
I have created another repository as user guide for this extension(updated title of this repository with the link). I will upload all feature workflows in a weeks time. As you have requested , I have first uploaded the CSS3 transition workflow.
