### ISSUE TITLE
Vertical/horizontal split switch in SplitView

### ISSUE THREAD

**Issue by zergius-eggstream** [swmitra/html-designer#4]
On vertical displays vertical split looks pathetic as two very thin columns. If, in addition, sidebar enabled editor turns completely useless. Is it possible to add vertical/horizontal split switch in options?

**Comment by swmitra** [comment]
These are just few presets. You can always override that by re sizing and re positioning the windows as they are floating. Attaching an animation of how to do that. 

But yes, I will increase the number of presets eventually and I will make sure to include some horizontal presets in future , even better , if you can merge some preset positioning in the repo for vertical displays. you can look at ./view/ViewPresentationPresets.js for reference. 

![splitview](https://cloud.githubusercontent.com/assets/12087205/8955343/67ac1420-3609-11e5-97bf-14cdb36b45ea.gif)

**Comment by zergius-eggstream** [comment]
Thanks, it works

2015-07-29 13:22 GMT+03:00 Swagatam Mitra notifications@github.com:
