### ISSUE TITLE
Color Hinting not working in Html Desinger

### ISSUE THREAD

**Issue by ghost** [swmitra/html-designer#6]
Hi,
i am using version 2.0.5 of html designer but i am not getting any kind of color hinting on css properties. i hope their must be a solution for me. 

Some please help me. 
For those who are interested to help ......THANKS in advance !! 
- a poor brackets user :8ball:

**Comment by swmitra** [comment]
Can you please let me know the specific scenario where you are expecting color hinting?

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/13586412/10798606/aad43be0-7dd2-11e5-83b1-57e4a449f896.PNG)
Like ur video tutorials......i should get a color hinting in the panel marked by red color. 
i can't even edit the BG-color property any place on my document.

**Comment by ghost** [comment]
![capture2](https://cloud.githubusercontent.com/assets/13586412/10798772/6926cfc2-7dd3-11e5-935a-9da457486c7d.PNG)
i just can edit that property from the CSS toolbox panel. BUT there is no color hint available :( 
plz help me.

**Comment by swmitra** [comment]
Which platform it is? The thumbs on the gradient sliders are looking different! 

Is this on linux?

**Comment by ghost** [comment]
no i am on windows 10 free

**Comment by ghost** [comment]
& also the Settings panel (yellow colored on right sight) not worked yet :(

**Comment by swmitra** [comment]
Is there any error in the console?

**Comment by ghost** [comment]
i haven't found any error yet. it just does't work properly.

**Comment by ghost** [comment]
Please Let me know if u got any solution. Until then i am sticking with my hard coding.
"Html Designer" is a greatest tool i have ever seen. Try to make to it more Robust so that every user can use the great tool :)
